// src/angular/components/payment-button.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ElementRef,
  OnInit,
  OnDestroy,
  ViewChild,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
} from '@angular/core';
import { Subscription } from 'rxjs';
import { SquareSdkService } from '../services/square-sdk.service.js';
import type { GooglePay, ApplePay, DigitalWalletOptions, TokenResult } from '../types.js';

/**
 * Payment button component for Google Pay / Apple Pay
 *
 * @example
 * ```html
 * <square-payment-button
 *   type="googlePay"
 *   (payment)="onPayment($event)"
 *   (error)="onError($event)"
 * ></square-payment-button>
 *
 * <square-payment-button
 *   type="applePay"
 *   [buttonOptions]="{ buttonColor: 'black' }"
 *   (payment)="onPayment($event)"
 * ></square-payment-button>
 * ```
 */
@Component({
  selector: 'square-payment-button',
  standalone: true,
  template: `
    <div
      #buttonContainer
      [style.minHeight.px]="48"
      [style.cursor]="ready && !loading ? 'pointer' : 'default'"
      [style.opacity]="loading ? 0.7 : 1"
      (click)="handleClick()"
      role="button"
      [attr.tabindex]="ready ? 0 : -1"
      [attr.aria-disabled]="!ready || loading"
      [attr.aria-label]="'Pay with ' + (type === 'googlePay' ? 'Google Pay' : 'Apple Pay')"
    ></div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PaymentButtonComponent implements OnInit, OnDestroy {
  /** Payment method type */
  @Input() type: 'googlePay' | 'applePay' = 'googlePay';

  /** Button styling options */
  @Input() buttonOptions?: DigitalWalletOptions;

  /** Emits when button is ready */
  @Output() buttonReady = new EventEmitter<void>();

  /** Emits payment token on success */
  @Output() payment = new EventEmitter<string>();

  /** Emits when an error occurs */
  @Output() error = new EventEmitter<Error>();

  /** Emits when payment is cancelled */
  @Output() cancel = new EventEmitter<void>();

  @ViewChild('buttonContainer', { static: true })
  private containerRef!: ElementRef<HTMLElement>;

  private paymentMethod: GooglePay | ApplePay | null = null;
  private subscription?: Subscription;

  ready = false;
  loading = false;

  constructor(
    private sdk: SquareSdkService,
    private cdr: ChangeDetectorRef
  ) {}

  ngOnInit(): void {
    this.subscription = this.sdk.whenReady().subscribe({
      next: (payments) => {
        void this.initializePaymentMethod(payments);
      },
      error: (err: Error) => {
        this.error.emit(err);
      },
    });
  }

  ngOnDestroy(): void {
    this.subscription?.unsubscribe();
    if (this.paymentMethod) {
      void this.paymentMethod.destroy();
      this.paymentMethod = null;
    }
  }

  handleClick(): void {
    if (!this.paymentMethod || this.loading) {
      return;
    }

    void this.tokenize();
  }

  private async initializePaymentMethod(
    payments: import('../types.js').Payments
  ): Promise<void> {
    try {
      if (this.type === 'googlePay') {
        this.paymentMethod = await payments.googlePay({});
      } else {
        this.paymentMethod = await payments.applePay({});
      }

      await this.paymentMethod.attach(
        this.containerRef.nativeElement,
        this.buttonOptions
      );

      this.ready = true;
      this.buttonReady.emit();
      this.cdr.markForCheck();
    } catch (err) {
      const error = err instanceof Error ? err : new Error(`Failed to initialize ${this.type}`);
      this.error.emit(error);
      this.cdr.markForCheck();
    }
  }

  private async tokenize(): Promise<void> {
    if (!this.paymentMethod) {
      return;
    }

    this.loading = true;
    this.cdr.markForCheck();

    try {
      const result: TokenResult = await this.paymentMethod.tokenize();

      if (result.status === 'OK' && result.token) {
        this.payment.emit(result.token);
      } else if (result.status === 'Cancel') {
        this.cancel.emit();
      } else {
        const errorMessage =
          result.errors?.map((e) => e.message).join(', ') ?? 'Payment failed';
        throw new Error(errorMessage);
      }
    } catch (err) {
      const error = err instanceof Error ? err : new Error('Payment failed');
      this.error.emit(error);
    } finally {
      this.loading = false;
      this.cdr.markForCheck();
    }
  }
}

// src/react/components/PaymentButton.tsx
import React, { useEffect, useRef, useState, useCallback } from 'react';
import { useSquare } from '../SquareProvider.js';
import type { GooglePay, ApplePay, DigitalWalletOptions, TokenResult } from '../types.js';

/**
 * Payment method type
 */
export type PaymentMethodType = 'googlePay' | 'applePay';

/**
 * Props for PaymentButton component
 */
export interface PaymentButtonProps {
  /** Payment method type */
  type: PaymentMethodType;
  /** Amount to display/charge (for display purposes) */
  amount?: number;
  /** Currency code */
  currency?: string;
  /** Button styling options */
  buttonOptions?: DigitalWalletOptions;
  /** Additional CSS class name */
  className?: string;
  /** Inline styles for the container */
  style?: React.CSSProperties;
  /** Callback when payment method is ready */
  onReady?: () => void;
  /** Callback when payment is successful */
  onPayment?: (token: string) => void;
  /** Callback when an error occurs */
  onError?: (error: Error) => void;
  /** Callback when payment is cancelled */
  onCancel?: () => void;
}

/**
 * Digital wallet payment button (Google Pay / Apple Pay)
 *
 * @example
 * ```tsx
 * import { PaymentButton } from '@bates/squareup/react';
 *
 * function Checkout() {
 *   const handlePayment = async (token: string) => {
 *     // Send token to your server to complete payment
 *     const response = await fetch('/api/payments', {
 *       method: 'POST',
 *       headers: { 'Content-Type': 'application/json' },
 *       body: JSON.stringify({ sourceId: token, amount: 1000 }),
 *     });
 *   };
 *
 *   return (
 *     <div>
 *       <PaymentButton
 *         type="googlePay"
 *         amount={1000}
 *         currency="USD"
 *         onPayment={handlePayment}
 *         onError={(err) => console.error('Error:', err)}
 *       />
 *       <PaymentButton
 *         type="applePay"
 *         amount={1000}
 *         currency="USD"
 *         onPayment={handlePayment}
 *         onError={(err) => console.error('Error:', err)}
 *       />
 *     </div>
 *   );
 * }
 * ```
 */
export function PaymentButton({
  type,
  amount: _amount,
  currency: _currency,
  buttonOptions,
  className,
  style,
  onReady,
  onPayment,
  onError,
  onCancel,
}: PaymentButtonProps) {
  const { payments, sdkLoaded, error: sdkError } = useSquare();
  const containerRef = useRef<HTMLDivElement>(null);
  const paymentMethodRef = useRef<GooglePay | ApplePay | null>(null);

  const [ready, setReady] = useState(false);
  const [loading, setLoading] = useState(false);
  const [_error, setError] = useState<Error | null>(sdkError);

  // Initialize payment method
  useEffect(() => {
    if (!sdkLoaded || !payments || !containerRef.current) {
      return;
    }

    let mounted = true;

    async function initializePaymentMethod() {
      if (!payments) return;

      try {
        let paymentMethod: GooglePay | ApplePay;

        if (type === 'googlePay') {
          paymentMethod = await payments.googlePay({});
        } else {
          paymentMethod = await payments.applePay({});
        }

        if (!mounted || !containerRef.current) {
          await paymentMethod.destroy();
          return;
        }

        await paymentMethod.attach(containerRef.current, buttonOptions);

        // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
        if (!mounted) {
          await paymentMethod.destroy();
          return;
        }

        paymentMethodRef.current = paymentMethod;
        setReady(true);
        setError(null);
        onReady?.();
      } catch (err) {
        if (!mounted) return;
        const error = err instanceof Error ? err : new Error(`Failed to initialize ${type}`);
        setError(error);
        onError?.(error);
      }
    }

    void initializePaymentMethod();

    return () => {
      mounted = false;
      if (paymentMethodRef.current) {
        void paymentMethodRef.current.destroy();
        paymentMethodRef.current = null;
      }
    };
  }, [sdkLoaded, payments, type, buttonOptions, onReady, onError]);

  // Handle click/tap on the button
  const handleClick = useCallback(async () => {
    if (!paymentMethodRef.current || loading) return;

    setLoading(true);
    setError(null);

    try {
      const result: TokenResult = await paymentMethodRef.current.tokenize();

      if (result.status === 'OK' && result.token) {
        onPayment?.(result.token);
      } else if (result.status === 'Cancel') {
        onCancel?.();
      } else {
        const errorMessage =
          result.errors?.map((e) => e.message).join(', ') ?? 'Payment failed';
        throw new Error(errorMessage);
      }
    } catch (err) {
      const error = err instanceof Error ? err : new Error('Payment failed');
      setError(error);
      onError?.(error);
    } finally {
      setLoading(false);
    }
  }, [loading, onPayment, onCancel, onError]);

  // Update error state when SDK error changes
  useEffect(() => {
    if (sdkError) {
      setError(sdkError);
      onError?.(sdkError);
    }
  }, [sdkError, onError]);

  return (
    <div
      ref={containerRef}
      className={className}
      style={{
        minHeight: '48px',
        cursor: ready && !loading ? 'pointer' : 'default',
        opacity: loading ? 0.7 : 1,
        ...style,
      }}
      onClick={() => { void handleClick(); }}
      role="button"
      tabIndex={ready ? 0 : -1}
      aria-disabled={!ready || loading}
      aria-label={`Pay with ${type === 'googlePay' ? 'Google Pay' : 'Apple Pay'}`}
    />
  );
}
